dist: bionic
language: rust
sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - deadsnakes 
    packages:
      - python3.9

rust:
  - nightly

cargo: cargo

cache:
  pip: true
  
before_install:
  - python3.9 -m ensurepip --upgrade
  - python3.9 -m pip install maturin

before_script:
  - cd imposclib && maturin build --interpreter python3.9 --release --strip cd ..

script:
  - cd imposclib && cargo test && cd ..
  - cd imposc && python3.9 -m pip install -r requirements-dev.txt && python3.9 -m pytest
  # - docker-compose -f docker-compose.test.yml up

# before_deploy:
#   - docker build -t happyleader/imposcr ./imposc

# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master