language: rust
sudo: required
services:
  - docker

rust:
  - nightly

cargo: cargo

script:
  - cd imposclib && cargo test && cd ..
  - docker-compose -f docker-compose.test.yml up

before_deploy:
  - docker build -t happyleader/imposcr ./imposc

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master