dist: bionic
language: rust
sudo: required
services:
  - docker

addons:
  apt:
    sources:
      - deadsnakes 
    packages:
      - python3.9

rust:
  - nightly
  
cache: cargo

cargo: cargo

# cache:
#   pip: true
# before_install:
#   # Upgrade pip
#   - sudo python3.9 -m pip install --quiet --upgrade pip

script:
  - cd imposclib && cargo test && cd ..
  # - docker-compose -f docker-compose.test.yml up

# before_deploy:
#   - docker build -t happyleader/imposcr ./imposc

# deploy:
#   provider: script
#   script: bash docker_push
#   on:
#     branch: master
