# Use latest because maturin requires a nightly build
FROM rust:latest as builder
WORKDIR /imposclib
COPY ./imposclib .
RUN cargo build

CMD [ "cargo", "test" ]


# RUN docker run --rm -v $(pwd):/io konstin2/maturin build --release
FROM konstin2/maturin as maturin
COPY --from=builder /imposclib /io
WORKDIR /io
RUN /usr/bin/maturin build --interpreter python3.9 --release --strip
# ENTRYPOINT ["/usr/bin/maturin"]
# CMD ["build", "--release", "--strip"]
# CMD ["develop", "--release", "--strip"]
CMD ["develop", "--help"]

FROM python:3.9-slim-buster
COPY --from=maturin /io/target/wheels /imposclib

WORKDIR /imposc

COPY ./imposc .

RUN python -m pip install -r requirements-dev.txt

RUN ls /imposclib/* |xargs python -m pip install 

ENV PYTHONPATH="/imposc"

# # ENTRYPOINT [ "/imposclib/imposclib/.venv/bin/python", "-m" ]

CMD [ "uvicorn", "main:app", "--reload" ]
