version: '3'
services: 
  test_rust:
    stdin_open: true
    build: 
      context: ./imposclib
      dockerfile: Dockerfile.dev
    volumes: 
      - ./imposclib:/imposclib
  test_python:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./imposc:/imposc
    command: ["pytest"]
  ui-tests:
    stdin_open: true
    build:
      context: ./imposc/static
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./imposc/static:/app
    command: ["npm", "test"]